method: transient
split: test
mde: MiDaS
img-key: midas_image
in-type: torch
in-order: nchw
out-type: numpy
out-order: nhwc
transform:
  - crop_image_and_depth
  - midas_preprocess
  - to_tensor
pre-cropped: True

min-depth: 0.1
max-depth: 10

refl-est: gray
source-n-sid-bins: 140
source-alpha: 0.1
source-beta: 10
