name: spad-single

channels:
  - pytorch

dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - configargparse
  - pyyaml
# - cudatoolkit=10.0   # Uncomment + replace with cuda version you're using.
  - h5py
  - scipy
  - scikit-image
  - tqdm
  - keras=2.2.4
  - pip
  - pip:
      - opencv-python
      - tensorflow<1.14
